### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by AhmadHRai** [202212-GIZ-YE-FEW/Tabadul#130]
**Task title**
Create Profile Page

**Task description**
Create Profile Page for users that have signed in

**Subtasks**

- [x] Add Profile Details Component 
- [x] Create My Items Component 
- [ ] Make the data dynamic

**Screenshots**
![image](https://user-images.githubusercontent.com/72130324/235676621-b090f87c-aa32-423c-a002-8be800eeac7f.png)

**Link to the component on Figma**
[Put the link here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?node-id=135-1957&t=9IkPmafaduaWlAtS-0)
