### ISSUE TITLE
Add Filter to Item Listed By Category

### ISSUE THREAD

**Issue by YassinAbdulrahman** [202212-GIZ-YE-FEW/Tabadul#26]
**Task title**
Add Filter to Item Listed By Category. 

**Task description**
- [x] Add New Component with it's Design For Categories .
- [x] Add Competent Listed Item 
- [x] Make Them dynamic So What Ever in DB Show there .
- [x] Add Functionality Any  Category I Click it Does Show Change The Content of The Cards.
- [x] Add Functionality For Search with it's Desgin
**Screenshots**
![Capture](https://user-images.githubusercontent.com/107113173/228644738-15d0b246-cf33-43a4-9118-353a2282c09d.JPG)

Figma Link

[Click here](https://www.figma.com/file/qPnL9lWyzueSXanLXNtkDG/let's-share-(Copy)?node-id=10-3&t=xaBU6ZMsJIYHyZDe-0)
