### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by YassinAbdulrahman** [202212-GIZ-YE-FEW/Tabadul#49]
**Task title**
404 Page 

**Task description**
404 Page Designing For Not found Route . 

- [x] Creating The Element 
- [x] Styling the Element 
- [x] Push the Changes 

**Screenshots**
![404](https://user-images.githubusercontent.com/107113173/230397475-3e2e6790-d705-431d-867c-3f9038ae2a19.JPG)
