### ISSUE TITLE
Fix products and blogs in HomePage 

### ISSUE THREAD

**Issue by SarahSalem-hub** [202212-GIZ-YE-FEW/Tabadul#83]
### Tasks:

- [x] **Fix products images** 
- [x] **Limit the shown Products for 5 items** 
- [x] **Limit the shown Blogs for 4 items**
